version: '3.8'

services:
 backend:
  build: ./
  ports:
   - 5000:5000
  env_file:
   - .env.production
  volumes:
   - backend:/data/backend
  depends_on:
   - mongo

 mongo:
  image: mongo:4.2.8
  ports:
   - 27017:27017
  volumes:
   - mongodb:/data/db
   - mongodb_config:/data/configdb
volumes:
 mongodb:
 mongodb_config:
 backend: